### PR TITLE
Java script popup menu

### PR DESCRIPTION
**Pull request by AliRezaBmeDu**
## Changes

- Added a pop-up menu for when a user clicks the hamburger icon
- Linked items in popup to items on page
- Used Javascript to interact with elements on the page

### CODE REVIEW

**Review by divinecharlotte — CHANGES_REQUESTED** [review]
Hi @Team  , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 

- Branch named well👍 
- Descriptive readme 👍 

 




 

## Required Changes ♻️
☠️ next time consider making sure that all the files you touched are available in the final commit you make for the reviewers to highlight the code which might have a problem to b e fixed and thta will also help you to easly see what changes are being requested
- [ ] Kindly consider making sure that the mobile menu links are only available on mobile screen size only for better design implementation. below is a screenshot showing you that even on the laptop screen it still dissapear
Screen Shot 2023-06-26 at 14 40 34

- [ ] kindly consider making sure that a user clicks one of the mobile menu links only the right part of your page is displayed and the whole nal link is not being displayed  because currently yes you are displaying the right part but when I scroll up I can see the nav links are still available fis that for the better user experience check the screen shoot below to see where the problem is arising from
Screen Shot 2023-06-26 at 14 37 32


_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by paulshaun-kdtk** [comment]
Hi @divinecharlotte please kindly elaborata on ur suggestions and how to implement as I'm not entirely sure on how to move forward.

**Comment by paulshaun-kdtk** [comment]
To the next reviewer... please note she ignored me for an elaboration; so please kindly elaborate on what she was trying to tell me(if indeed I did not implement it already): before you mark my PR as needing changes as I only have a limited number of reviews... thank you.

**Review by muneebulrehman — CHANGES_REQUESTED** [review]
Hi @AliRezaBmeDu , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- No linter errors
- Descriptive PR

 ## Required Changes ♻️
_Check the comments under the review._

The mobile menu should only be visible on the mobile screens. That part I believe is self-explanatory. However, when switching from the mobile version to the desktop, the hamburger menu is still present which it should not and it still opens a menu that is only for mobile screens. I have recorded a video trying to demonstrate the issue. Kindly fix this issue before submitting for a re-review.

https://github.com/paulshaun-kdtk/Microverse_Proffessional_Portifolio/assets/33268927/a019fbc5-5e40-44f2-af60-99ec2f314194

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [ ] One of the project requirements for this milestone is to implement javascript linter check which I see is missing in your case. Since the previous reviewer didn't raise this requirement as required, I am marking this as Optional. However, i strongly recommend you implement this as this will needed for all the sections from here on.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by divinecharlotte — APPROVED** [review]
# Hello @paulshaun-kdtk    😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say  👍🏻 ✅ 
### To Highlight 💯


- Descriptive PR👍 
- Good implementation of the required changes 👍 
 




## Congratulations! 🎉 



Cheers, and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
